/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../Pages/About.vue')['default']
    Home: typeof import('./../Pages/Home.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
  }
}
